import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import TopBar from "@/components/TopBar";
import ServerAwaker from "@/components/ServerAwaker"; // ✨ นำเข้า ServerAwaker

const sarabun = Sarabun({
	variable: "--font-sarabun",
	subsets: ["latin", "thai"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "ระบบติดตามงานมอบหมาย",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn("h-full", "antialiased", "font-sans", sarabun.variable)}
			suppressHydrationWarning
		>
			<body className="flex min-h-full flex-col">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
                    {/* ✨ ห่อทุกอย่างด้วยหน้ากากโหลดปลุกเซิร์ฟเวอร์ */}
                    <ServerAwaker>
                        <header>
                            <TopBar></TopBar>
                        </header>
                        {children}
                    </ServerAwaker>
				</ThemeProvider>
			</body>
		</html>
	);
}